openapi: 3.2.0
info:
  title: 'A sample API conforming to the standard OGC API - Processes - Part 1 : Core Process Description API'
  version: 1.0.0
  description: This document is an API definition document provided alongside the OGC API - Processes standard. The OGC API - Processes Standard specifies a processing interface to communicate over a RESTful protocol using JavaScript Object Notation (JSON) encodings. The specification allows for the wrapping of computational tasks into executable processes that can be offered by a server and be invoked by a client application.
  contact:
    name: Open Geospatial Consortium (OGC)
    email: standards-team@ogc.org
    url: https://www.ogc.org/contacts
  license:
    name: OGC license
    url: http://www.ogc.org/legal/
servers:
- description: Example server
  url: http://example.org/ogcapi
tags:
- name: ProcessDescription
paths:
  /processes/{processID}:
    get:
      summary: retrieve a process description
      description: 'The process description contains information about inputs and outputs and a link to the execution-endpoint for the process. The Core does not mandate the use of a specific process description to specify the interface of a process. That said, the Core requirements class makes the following recommendation:


        Implementations SHOULD consider supporting the OGC process description.


        For more information, see [Section 7.10](https://docs.ogc.org/is/18-062/18-062.html#sc_process_description).

        '
      operationId: getProcessDescription
      tags:
      - ProcessDescription
      parameters:
      - $ref: https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/parameters/processIdPathParam.yaml
      responses:
        200:
          $ref: https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/responses/ProcessDescription.yaml
        404:
          $ref: https://schemas.opengis.net/ogcapi/processes/part1/1.0/openapi/responses/NotFound.yaml
